name: Build and Publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out code
            - name: Check out code
              uses: actions/checkout@v3

            # Step 2: Log in to GitHub Container Registry (if private images are used)
            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Step 3: Build and run the Docker container
            - name: Build Docker image
              run: docker build -t my-maturin-project .

            # Step 4: Publish the package to PyPI
            - name: Publish to PyPI
              env:
                  PYPI_USERNAME: __token__
                  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
              run: |
                  docker run --rm \
                    -e PYPI_USERNAME=$PYPI_USERNAME \
                    -e PYPI_PASSWORD=$PYPI_PASSWORD \
                    my-maturin-project \
                    maturin publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
